### ISSUE TITLE
Read only issue when syncing localToCloud in Docker container

### ISSUE THREAD

**Issue by almliden** [FilenCloudDienste/filen-sync#60]
**Describe the bug**

I'm using the `file/cli:latest` (currently 0.0.32) docker image and mounting a volume into it as readonly. I'm having issues with the `sync` command which exits with the error message `cycleLocalSmokeTestFailed`. It seems to be related to the folder being readonly since switching to read/write makes it work again.

**To Reproduce**

1. Start a container with the following docker compose file:
```yml
services:
  filen-cli:
    image: filen/cli:latest
    restart: unless-stopped
    container_name: filen-cli
    volumes:
      - /mnt/hdd:/data/hdd:ro
    environment:
      FILEN_EMAIL: $FILEN_EMAIL
      FILEN_PASSWORD: $FILEN_PASSWORD
    command: >
      sync
          /data/hdd:localToCloud:/cloud1
          --continuous
          --verbose
```
2. Look at the logs for the container and see that the error `cycleLocalSmokeTestFailed` is thrown. 

**Expected behavior**

I would expect the command to succeed and not throw an error. I'm not sure about it, but it looks like it could be called from somewhere here: https://github.com/FilenCloudDienste/filen-sync/blob/6ac27d5c687fc44bfd932ea51f77b98766613aef/src/lib/sync.ts#L103 I do find it weird that it fails on that check since the mode used is `localToCloud`, and the only modes that requires r/w are `cloudBackup`, `cloudToLocal` or `twoWay` according to the above reference where `isPathWritable` is called.

**Additional context**

Could possible be an issue with Docker and the permissions on the files from the outside. When removing `:ro` from the volume it starts to work though.
Let me know if anything is missing or more details are needed!
